# Nome do fluxo de trabalho
name: Gerar Calendário ICS

# Gatilho: Executar sempre que houver uma alteração na branch 'main'
on:
  push:
    branches:
      - main
      
      
permissions:
  contents: write
  pages: write
  id-token: write

# Tarefas a serem executadas
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Pega o código do seu repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Instala as bibliotecas necessárias (do arquivo requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Executa seu script de conversão
      - name: Run CSV to ICS script
        run: python csv_para_ics.py

      # 5. Salva o arquivo .ics atualizado de volta no repositório
      - name: Commit and push if it changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add calendario_noven.ics calendario_noven_desenvolvimento.ics calendario_patoge.ics calendario_patoge_desenvolvimento.ics
          git diff --staged --quiet || git commit -m "Atualiza calendario_noven.ics"
          git push
